(maint) add assertions to eventmachine thread helpers
Here we beef up the newly-extracted {start,stop}_eventmachine_thread
helpers to give us more insight as to what's going on with eventmachine.

It should help in diagnosing this class of failing test:

    * On each agent, test that a 2nd association has occurred
    RuntimeError: An Eventmachine reactor needs to be running
    /var/lib/jenkins/workspace/platform_pxp-agent_intn-van-sys_stable/SLAVE_LABEL/beaker/TEST_TARGET/windows2012r2-64a/acceptance/tests/reconnect_after_broker_unavailable.rb:25
    /var/lib/jenkins/workspace/platform_pxp-agent_intn-van-sys_stable/SLAVE_LABEL/beaker/TEST_TARGET/windows2012r2-64a/acceptance/tests/reconnect_after_broker_unavailable.rb:24
    /var/lib/jenkins/workspace/platform_pxp-agent_intn-van-sys_stable/SLAVE_LABEL/beaker/TEST_TARGET/windows2012r2-64a/acceptance/tests/reconnect_after_broker_unavailable.rb:24
    /var/lib/jenkins/workspace/platform_pxp-agent_intn-van-sys_stable/SLAVE_LABEL/beaker/TEST_TARGET/windows2012r2-64a/acceptance/tests/reconnect_after_broker_unavailable.rb:24
    /var/lib/jenkins/workspace/platform_pxp-agent_intn-van-sys_stable/SLAVE_LABEL/beaker/TEST_TARGET/windows2012r2-64a/acceptance/tests/reconnect_after_broker_unavailable.rb:23
    /usr/local/rvm/gems/ruby-2.1.1/gems/beaker-2.34.0/bin/beaker:6
    /usr/local/rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15
    /usr/local/rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15